const breakSchedules = {
    "22/01/2020": [
        {
            employee: "CoWorker 1", 
            startTime: "10:00",
            endTime: "10:15",
            duration: 15,
            floater: 1,
            breakNum: 1,
        },
        {
            employee: "CoWorker 2", 
            startTime: "10:00",
            endTime: "10:15",
            duration: 15,
            floater: 2,
            breakNum: 1,
        },
        {
            employee: "CoWorker 3", 
            startTime: "10:15",
            endTime: "10:30",
            duration: 15,
            floater: 1,
            breakNum: 1,
        },
        {
            employee: "CoWorker 4", 
            startTime: "10:15",
            endTime: "10:30",
            duration: 15,
            floater: 2,
            breakNum: 1,
        },
        {
            employee: "CoWorker 1", 
            startTime: "10:30",
            endTime: "11:00",
            duration: 30,
            floater: 1,
            breakNum: 1,
        },
        {
            employee: "CoWorker 2", 
            startTime: "10:30",
            endTime: "11:00",
            duration: 30,
            floater: 2,
            breakNum: 1,
        },
        {
            employee: "CoWorker 3", 
            startTime: "11:00",
            endTime: "11:30",
            duration: 30,
            floater: 1,
            breakNum: 1,
        },
        {
            employee: "CoWorker 4", 
            startTime: "11:00",
            endTime: "11:30",
            duration: 30,
            floater: 2,
            breakNum: 1,
        },
        {
            employee: "CoWorker 1", 
            startTime: "11:30",
            endTime: "11:45",
            duration: 15,
            floater: 1,
            breakNum: 2,
        },
        {
            employee: "CoWorker 2", 
            startTime: "11:30",
            endTime: "11:45",
            duration: 15,
            floater: 2,
            breakNum: 2,
        },
        {
            employee: "CoWorker 3", 
            startTime: "11:45",
            endTime: "12:00",
            duration: 15,
            floater: 1,
            breakNum: 2,
        },
        {
            employee: "CoWorker 4", 
            startTime: "11:45",
            endTime: "12:00",
            duration: 15,
            floater: 2,
            breakNum: 2,
        },
    ],
    "23/01/2020": [
        {
            employee: "Person 1", 
            startTime: "10:00",
            endTime: "10:15",
            duration: 15,
            floater: 1,
        },
        {
            employee: "Person 2", 
            startTime: "10:00",
            endTime: "10:15",
            duration: 15,
            floater: 2,
        },
        {
            employee: "Person 3", 
            startTime: "10:15",
            endTime: "10:30",
            duration: 15,
            floater: 1,
        },
        {
            employee: "Person 4", 
            startTime: "10:15",
            endTime: "10:30",
            duration: 15,
            floater: 2,
        },
    ],
    "24/01/2020": [
        {
            employee: "Brother 1", 
            startTime: "10:00",
            endTime: "10:15",
            duration: 15,
            floater: 1,
        },
        {
            employee: "Brother 2", 
            startTime: "10:00",
            endTime: "10:15",
            duration: 15,
            floater: 2,
        },
        {
            employee: "Brother 3", 
            startTime: "10:15",
            endTime: "10:30",
            duration: 15,
            floater: 1,
        },
        {
            employee: "Brother 4", 
            startTime: "10:15",
            endTime: "10:30",
            duration: 15,
            floater: 2,
        },
    ],
    "25/01/2020": [
        {
            employee: "Sister 1", 
            startTime: "10:00",
            endTime: "10:15",
            duration: 15,
            floater: 1,
        },
        {
            employee: "Sister 2", 
            startTime: "10:00",
            endTime: "10:15",
            duration: 15,
            floater: 2,
        },
        {
            employee: "Sister 3", 
            startTime: "10:15",
            endTime: "10:30",
            duration: 15,
            floater: 1,
        },
        {
            employee: "Sister 4", 
            startTime: "10:15",
            endTime: "10:30",
            duration: 15,
            floater: 2,
        },
    ],
}

// const breakSchedules = {
//     "22/01/2020": [
//         ["CoWorker 1", "10:00 - 10:15", 15, 1]
//     ]
// }

export default breakSchedules