const breakSchedules = {
    "26/01/2020": {
        totalFifteens: 8,
        totalThirties: 4,
        totalBreakTime: 240,
        goalTime: 0,
        breaks: [
            {
                employee: "CoWorker 1", 
                startTime: "10:00",
                endTime: "10:15",
                duration: 15,
                floater: 1,
                breakNum: 1,
            },
            {
                employee: "CoWorker 2", 
                startTime: "10:00",
                endTime: "10:15",
                duration: 15,
                floater: 2,
                breakNum: 1,
            },
            {
                employee: "CoWorker 3", 
                startTime: "10:15",
                endTime: "10:30",
                duration: 15,
                floater: 1,
                breakNum: 1,
            },
            {
                employee: "CoWorker 4", 
                startTime: "10:15",
                endTime: "10:30",
                duration: 15,
                floater: 2,
                breakNum: 1,
            },
            {
                employee: "CoWorker 1", 
                startTime: "10:30",
                endTime: "11:00",
                duration: 30,
                floater: 1,
                breakNum: 1,
            },
            {
                employee: "CoWorker 2", 
                startTime: "10:30",
                endTime: "11:00",
                duration: 30,
                floater: 2,
                breakNum: 1,
            },
            {
                employee: "CoWorker 3", 
                startTime: "11:00",
                endTime: "11:30",
                duration: 30,
                floater: 1,
                breakNum: 1,
            },
            {
                employee: "CoWorker 4", 
                startTime: "11:00",
                endTime: "11:30",
                duration: 30,
                floater: 2,
                breakNum: 1,
            },
            {
                employee: "CoWorker 1", 
                startTime: "11:30",
                endTime: "11:45",
                duration: 15,
                floater: 1,
                breakNum: 2,
            },
            {
                employee: "CoWorker 2", 
                startTime: "11:30",
                endTime: "11:45",
                duration: 15,
                floater: 2,
                breakNum: 2,
            },
            {
                employee: "CoWorker 3", 
                startTime: "11:45",
                endTime: "12:00",
                duration: 15,
                floater: 1,
                breakNum: 2,
            },
            {
                employee: "CoWorker 4", 
                startTime: "11:45",
                endTime: "12:00",
                duration: 15,
                floater: 2,
                breakNum: 2,
            },
        ], 
    },
}

export default breakSchedules